name: Publish Be Dev
on:
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: publish
        uses: anton-nagornyi/anyit-be-dev/.github/composite-actions/publish@main
        with:
          working-directory: ./
          npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
